# -*- coding: utf-8 -*-
"""atividade6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1igG6-dITAUh7LpvDtvhTKdtjbDuy1sVw
"""

#receber 2 valores e imprimir o menor

def retornarMenor(x,y) :
  if x<y :
    return x
  elif y<x :
    return y
  else :
    return 'são o mesmo número'
numeroUm = int(input('insira o primeiro valor: '))
numeroDois = int(input('insira o segundo valor: '))
print(retornarMenor(numeroUm,numeroDois))

#positivo ou negativo

def positivoNegativo (x) :
  if x >=0 :
    return 'positivo'
  else :
    return 'negativo'
numero = int(input('insira um número: '))
print(positivoNegativo(numero))

#limite

def somaLimite (x,y,z) :
  if x+y <= limite :
    return 'o valor somado é menor ou igual o limite'
  else :
    return 'o valor excede o limite'
numeroUm = int(input('insira o primeiro numero: '))
numeroDois = int(input('insira o segundo numero: '))
limite = int(input('insira o limite: '))
print(somaLimite(numeroUm, numeroDois, limite))

#fizzbuzz

def fizzBuzz (x) :
  if x%3==0 and x%5==0 :
    print('fizzBuzz')
  elif x%3==0 :
    print('fizz')
  elif x%5==0 :
    print('buzz')
  else :
    print(x)
n = int(input('insira um número: '))
fizzBuzz(n)

#lista

def listaNum (a,b) :
  if b.count(a) == True :
    return 'o numero está na lista'
  else :
    return 'o numero não está na lista'
n = int(input('insira um número: '))
lista = [1,2,3,4,5]
print(listaNum(n,lista))

#soma inteiros positivos n

def somaNum (x) :
    if x == 0 :
      return 0
    else:
      return x + somaNum(x-1)
n = int(input('insira um número: '))
print(somaNum(n))