# -*- coding: utf-8 -*-
"""atividade3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dyPBtTySTFO6q6DfvVhqPrZFdWJlwHQx
"""

#verificar se valores sao truthy ou false

print(bool('abc'))
print(bool(range(0)))
print(bool(123456.789))
print(bool(-5))
print(bool(None))
print(bool(not(False)))
print(bool(False))
print(bool(print()))

#empresa de vendas

catalogo = (20, 50, 100)
numCam = int(input('quantas camisetas vendidas?'))
numCal = int(input('quantas calças vendidas?'))
numSap = int(input('quantos sapatos vendidas?'))

vendas = [catalogo[0]*numCam, catalogo[1]*numCal, catalogo[2]*numSap]
#print(vendas)
print('total de vendas de camisetas: ', vendas[0])
print('total de vendas de calças: ', vendas[1])
print('total de vendas de sapatos: ', vendas[2])
print('total de vendas: ', vendas[0] + vendas[1] + vendas [2])

2