# -*- coding: utf-8 -*-
"""atividade1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FOdZB4yoVYGrk-bUQmBdtT81NL0qQG5e
"""

#atividade 1

printPhyton = 'python é demais!'
print(a)

#atividade 2

nomeCompleto = 'Marcos Vinicius Copello Freitas'
idade = '21'

print('meu nome é ' + nomeCompleto + ' e tenho ' + idade + ' anos')

#atividade 3

numeroX = int(input('informe um valor:'))
numeroY = int(input('infrome outro valor:'))
soma = numeroX + numeroY
sub = numeroX - numeroY
mult = numeroX * numeroY
div = numeroX/numeroY
print('o resultado de ' , numeroX , '+' , numeroY , ' é ' , soma)
print('o resultado de ' , numeroX , '-' , numeroY , ' é ' , sub)
print('o resultado de ' , numeroX , '*' , numeroY , ' é ' , mult)
print('o resultado de ' , numeroX , '/' , numeroY , ' é ' , div)

