# -*- coding: utf-8 -*-
"""atividade5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XRpFFjXg92_-xT9Fo7I-2X60hOv5LeB1
"""

#banco notas e moedas

valor = float(input('digite o valor desejado: '))
valor_em_centavos = int(valor * 100)

notas_100 = valor_em_centavos // 10000
valor_em_centavos -= notas_100 * 10000

notas_50 = valor_em_centavos // 5000
valor_em_centavos -= notas_50 * 5000

notas_20 = valor_em_centavos // 2000
valor_em_centavos -= notas_20 * 2000

notas_10 = valor_em_centavos // 1000
valor_em_centavos -= notas_10 * 1000

notas_5 = valor_em_centavos // 500
valor_em_centavos -= notas_5 * 500

notas_2 = valor_em_centavos // 200
valor_em_centavos -= notas_2 * 200

moedas_1 = valor_em_centavos // 100
valor_em_centavos -= moedas_1 * 100

moedas_50 = valor_em_centavos // 50
valor_em_centavos -= moedas_50 * 50

moedas_25 = valor_em_centavos // 25
valor_em_centavos -= moedas_25 * 25

moedas_10 = valor_em_centavos // 10
valor_em_centavos -= moedas_10 * 10

moedas_5 = valor_em_centavos // 5
valor_em_centavos -= moedas_5 * 5

moedas_1cent = valor_em_centavos

# exibe o resultado
print("NOTAS:")
print(f"{notas_100} nota(s) de R$ 100.00")
print(f"{notas_50} nota(s) de R$ 50.00")
print(f"{notas_20} nota(s) de R$ 20.00")
print(f"{notas_10} nota(s) de R$ 10.00")
print(f"{notas_5} nota(s) de R$ 5.00")
print(f"{notas_2} nota(s) de R$ 2.00")
print("MOEDAS:")
print(f"{moedas_1} moeda(s) de R$ 1.00")
print(f"{moedas_50} moeda(s) de R$ 0.50")
print(f"{moedas_25} moeda(s) de R$ 0.25")
print(f"{moedas_10} moeda(s) de R$ 0.10")
print(f"{moedas_5} moeda(s) de R$ 0.05")
print(f"{moedas_1cent} moeda(s) de R$ 0.01")

#mes match case (nao testado pois nao funciona no colab)

num = int(input('digite um número entre 1 e 12: '))

match num :
  case 1:
    print('janeiro')
  case 2:
    print('fevereiro')
  case 3:
    print('março')
  case 4:
    print('abril')
  case 5:
    print('maio')
  case 6:
    print('junho')
  case 7:
    print('julho')
  case 8:
    print('agosto')
  case 9:
    print('setembro')
  case 10:
    print('outubro')
  case 11:
    print('novembro')
  case 12:
    print('dezembro')

#financiamento

valor = float(input('digite o valor desejado para financiamento: '))
renda = float(input('digite sua renda mensal: '))
parcelas = int(input('digite o número de parcelas desejadas: '))

valor_parcela = valor/parcelas

if valor_parcela <= renda*0.3 and parcelas <=180 :
  print('financiamento aprovado')
  print('valor da parcela: R$:%.2f' %valor_parcela)
else :
  print('financiamento recusado')

#impostos 

salario = float(input('digite seu salario: '))

if salario <= 2000.00:
    imposto = 0
elif salario <= 3000.00:
    imposto = (salario - 2000.00) * 0.08
else:
    if salario <= 4500.00:
        imposto = (salario - 3000.00) * 0.18 + 1000.00 * 0.08
    else:
        imposto = (salario - 4500.00) * 0.28 + 1500.00 * 0.18 + 1000.00 * 0.08

print("imposto de renda a pagar: R$ %.2f" % imposto)

#fatorial de n

numero = int(input('digite um número inteiro: '))
fatorial = 1

if numero == 0:
    fatorial = 1
else:
    for i in range(1, numero + 1):
        fatorial *= i

print(numero,'!=', fatorial)

#palavrões

palavra = input('digite uma palavra: ')

if len(palavra) >= 10 :
  print('é um palavrão')
else :
  print('não é um palavrão')

#contador de donuts

numero = int(input('quantos donuts? '))

if numero <10 :
  print('number of donuts:',numero)
else :
  print('number of donuts:',numero,'many')

#string dois primeiros e dois ultimos

palavra = input('digite uma spring: ')

if len(palavra) < 3 :
  print('n/a')
else :
  print(f'{palavra[:2]}{palavra[-2:]}')

#substituir string *

stg = input("digite uma string: ")

prim_letra = stg[0]
resultado = prim_letra

for caractere in stg[1:]:
    if caractere == prim_letra:
        resultado += "*"
    else:
        resultado += caractere

print(resultado)